[2020-08-12 13:24:35.903462], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 43 'mode='lines',') : 
    Invalid value of type 'builtins.range' received for the 'x' property of scatter
        Received value: range(0, 66)

    The 'x' property is an array that may be specified as a tuple,
    list, numpy array, or pandas Series
[2020-08-12 13:26:46.813292], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 43 'mode='lines',') : 
    Invalid value of type 'builtins.range' received for the 'x' property of scatter
        Received value: range(0, 66)

    The 'x' property is an array that may be specified as a tuple,
    list, numpy array, or pandas Series
[2020-08-12 13:28:56.305926], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 43 'mode='lines',') : 
    Invalid value of type 'builtins.range' received for the 'x' property of scatter
        Received value: range(30, 97)

    The 'x' property is an array that may be specified as a tuple,
    list, numpy array, or pandas Series
[2020-08-12 13:30:44.853497], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 46 'graph = plotly.offline.plot({"data": data, "layout": layout},') : name 'layout' is not defined
[2020-08-12 15:31:03.838877], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 81 'perc_df.index = index') : Length mismatch: Expected axis has 61 elements, new values have 62 elements
[2020-08-12 15:31:05.102822], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:34:35.401329], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 83 'line_group=line_group)') : Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['5%', '95%'] but received: Age
[2020-08-12 15:34:36.504524], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:37:11.832537], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 82 'area = px.area(perc_df, color=color, line_group=line_group)') : All arguments should have the same length. The length of argument `line_group` is 2, whereas the length of  previously-processed arguments ['index', '5%', '95%'] is 61
[2020-08-12 15:37:12.989445], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:39:43.268187], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 83 'area = px.area(perc_df, color=color, line_group=line_group)') : Value of 'line_group' is not the name of a column in 'data_frame'. Expected one of ['5%', '95%'] but received: 5th Percentile to 95th Percentile Wealth (die at 89)
[2020-08-12 15:39:44.546381], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:42:13.959746], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 83 'area = px.area(perc_df, color=color)#, line_group=line_group)') : Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['5%', '95%'] but received: lightcyan
[2020-08-12 15:42:15.190520], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:45:00.808105], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 83 'area = px.area(perc_df, color=color, line_group=perc_df.columns)#, line_group=line_group)') : All arguments should have the same length. The length of argument `line_group` is 2, whereas the length of  previously-processed arguments ['index', '5%', '95%'] is 61
[2020-08-12 15:45:01.848211], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:47:20.350044], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotArea, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 83 'area = px.area(perc_df, color=color, line_group=line_group)#, line_group=line_group)') : Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['5%', '95%'] but received: lightcyan
[2020-08-12 15:47:21.465962], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 37 'fig = cls().plotArea(perc_df_1[['5%', '95%']], index1, line_group, color='lightcyan')') : local variable 'area' referenced before assignment
[2020-08-12 15:53:26.312113], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py Plot Asset Growth, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 116 'name = f'Median Wealth (die at {age})',') : name 'age' is not defined
[2020-08-12 15:53:27.572144], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py Plot Asset Growth, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 116 'name = f'Median Wealth (die at {age})',') : name 'age' is not defined
[2020-08-12 16:27:19.811415], ERROR Message : In /Users/kevin/常用/realtime_trading/site_project/Retirement Bot/Config.py plotWealths, Error :  In (/Users/kevin/常用/realtime_trading/site_project/Retirement Bot/PlotTool.py, Line 40 'fig1.append_trace(data)') : append_trace() missing 2 required positional arguments: 'row' and 'col'
[2020-08-12 17:21:44.529632], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py plotWealths, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\PlotTool.py, Line 40 'fig1.append_trace(data)') : append_trace() missing 2 required positional arguments: 'row' and 'col'
[2020-08-12 18:35:46.245073], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py message_process, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\RetirementBot.py, Line 44 'setting = usr_settings.get(chat_id, {})') : name 'usr_settings' is not defined
[2020-08-12 19:31:04.671179], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py message_process, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\RetirementBot.py, Line 64 'reply_setting_tool(bot, chat_id)') : name 'reply_setting_tool' is not defined
[2020-08-12 19:32:28.974759], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py message_process, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\RetirementBot.py, Line 48 'setAge(bot, chat_id, msg, settings)') : name 'settings' is not defined
[2020-08-12 19:48:51.885047], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py plotWealths, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\PlotTool.py, Line 37 'ax1.title.set_text('模擬從現在到退休到死亡(可能年齡)的資產狀態', fontproperties=ChineseFont, fontsize=20)') : set_text() got an unexpected keyword argument 'fontproperties'
[2020-08-12 19:54:38.114390], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py plotWealths, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\PlotTool.py, Line 37 'ax1.title.set_text('模擬從現在到退休到死亡(可能年齡)的資產狀態', fontdict={'fontproperties':ChineseFont, 'fontsize':20})') : set_text() got an unexpected keyword argument 'fontdict'
[2020-08-12 20:01:40.308676], ERROR Message : In D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\Config.py plotWealths, Error :  In (D:\RealTime_Kevin\realtime_trading\site_project\Retirement Bot\PlotTool.py, Line 36 'ax1 = plt.subplot(gs[:, :], ylabel='財富狀況(千元)', xlabel='年齡(歲)',fontproperties = ChineseFont)') : 'AxesSubplot' object has no property 'fontproperties'
